language: go
install: go get -v github.com/spf13/hugo
script:
  - git clone https://github.com/Cyber-Syndicates/cybersyndicates.com
  - cd cybersyndicates.com
  - hugo
notifications:
    email:
        on_failure: always
